### ISSUE TITLE
Two options

### ISSUE THREAD

**Issue by nikitastafeevone** [GermainZ/ActivityForceNewTask#10]
1)Example.In Xposed i am open browser.Then i am opening new tab,going some where else,reading something,going somewhere else.Then i am press back button.And then i am go to previous page in browser.Can you add on tapping on back button going to previous app(Xposed).
2)On tapping on back or home button close the opened app(browser in the first example).
I am dont know is it needed by another users.But thats the my ideas.

**Comment by GermainZ** [comment]
Sorry for the late reply, the email notification must've gotten lost.

> 1)Example.In Xposed i am open browser.Then i am opening new tab,going some where else,reading something,going somewhere else.Then i am press back button.And then i am go to previous page in browser.Can you add on tapping on back button going to previous app(Xposed).

This is out of scope for this module.

>  2)On tapping on back or home button close the opened app(browser in the first example).

Same. I'd suggest you ask for a new module that does this somewhere else (there's a thread on XDA for module ideas, someone might pick it up if they're interested). Good luck :)
